apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
      - name: my-container
        image: myapp_reverse
